### PR TITLE
Adding indexing and sliced iteration

### PR DESCRIPTION
**Pull request by trulsf**
Extending support for better indexing and iteration at operational level. The main use case is scheduling and production planning models with startup and shutdown modelling. Naming is up for discussion.

### CODE REVIEW

**Review by hellemo — COMMENTED** [review]
Looks like this can be useful.

When it comes to the naming, have you considered using similar names as for Iterators, or do you consider them conceptually different? I had `Iterators.partition` and `Iterators.cycle` in mind, which seem to offer similar capabilities. Slicing is normally a little different, but one can use `eachslice`, but as I understand that is more related to dimensions than partitioning by length or number of elements.

Also one idea, would it make sense to offer co-iteration of slices and their durations?

**Comment by trulsf** [comment]
I think both `Iterators.partition` and `Iterators.cycle` have a usage that does not align with the current functionality. I am currently leaning towards using the name `block` instead of slice. A block of time periods does not sound too bad. 

I am not sure co-iteration with duration is worth it as it should be fairly easy to get it by summing the duration of the time periods in the block.

**Comment by trulsf** [comment]
Another name alternative is `chunk`

**Comment by hellemo** [comment]
Good point, I think I would prefer block or chunk over slice.

**Pull request merged**
